# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'geD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for geD
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'SnapKit'
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리
  pod 'KeychainSwift', '~> 19.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'naveridlogin-sdk-ios'
  pod 'Kingfisher', '~> 6.0'
end
